config/routes.rb
Rails.application.routes.draw do
  root to:  'pages#home'
  resources :tasks,  except:  [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates_presence_of :title
  validate :future_completed_date

  private

  def future_completed_date
    if !completed.blank? && completed > Date.today
      self.errors.add(:completed, "can't be in the future")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @tasks = Task.all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
  @task = Task.new
  render :show_form
  end

  def create
    @task = Task.create(task_params)
    @tasks = Task.all

    save_task
  end

  def destroy
  @task = Task.find(params[:id])
  @task.destroy
  @tasks = Task.all
  end

  def edit
  @task = Task.find(params[:id])

  render :show_form
  end

  def update
  @task = Task.find(params[:id])
  @task.update_attributes(task_params)
  @tasks = Task.all

  save_task
  end

  private
  def task_params
    params.require(:task).permit(:title, :note, :completed)
  end

  def save_task
  if @task.save
    @tasks = Task.all
    render :hide_form
  else
    render :show_form
  end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Reminder
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .row-fluid
      .span10.offset1
        .hero-unit.text-center
          %h1
            Reminder
          %p
            Welcome to the tutorial's ToDo application
          = link_to 'New Task', new_task_path,  class:  'btn btn-primary input-large', remote: true
    = yield

app/views/pages/home.html.haml
#task-list.container
  = render partial: 'tasks/task_list', locals: {tasks: @tasks}
#modal.modal.fade

app/views/tasks/_task_form.html.haml
.modal-header
  %h1
    = task.new_record? ? 'New Task' : "Editing task"
= simple_form_for task, class: 'clearfix', remote: true do |f|
  .modal-body
    = f.input :title
    = f.input :note
    = f.input :completed, as: :string, input_html: { class: 'datepicker' }
  .modal-footer
    = f.submit 'Save', class: 'btn btn-primary'

app/views/tasks/_task_list.html.haml
- if tasks.empty?
  %span.text-warning There are no tasks!
- else
  %table.table.table-hover.table-bordered
    %thead
      %tr
        %th Title
        %th Created at
        %th Completed
        %th Actions
    %tbody
      - tasks.each do |task|
        %tr
          %td
            %strong= task.title
          %td.text-info= task.created_at
          %td.text-success= task.completed
          %td
            = link_to task_path(task), remote: true, method: :delete, data: {confirm: "Are you sure you want to delete task #{task.title}?"} do
              %i.icon-remove
            = link_to edit_task_path(task), remote: true do
              %i.icon-edit

app/views/tasks/destroy.js.erb
$('#task-list').html('<%= j(render partial: 'task_list', locals: {tasks: @tasks})%>');

app/views/tasks/hide_form.js.erb
$('#task-list').html('<%= j(render partial: 'tasks/task_list', locals: {tasks: @tasks}) %>');
$('#modal').modal('hide');

app/views/tasks/show_form.js.erb
m = $('#modal');
m.html('<%= j(render partial: 'task_form', locals: {task: @task}) %>');
m.modal('show');
$('#modal').integrateDatepicker();